feat:json extractor
FlatFilers/flatfile-plugins pull request #126
Opened 2023-07-19 19:28 UTC by carlbrugger

2023-07-20 15:26 UTC, hansjhoffman commented on plugins/json-extractor/package.json
> +    "node": ">= 12"
🔧 I think we decided on `16` here

2023-07-20 18:14 UTC, carlbrugger commented
Thanks for the feedback @hansjhoffman! 🌮

2023-07-21 13:35 UTC, ashleygmulligan2 requested changes
Run npm run changeset from root

2023-07-21 13:35 UTC, ashleygmulligan2 commented on plugins/json-extractor/package.json
> +  "version": "1.0.0",
let's do 0.0.1 for first release

2023-07-25 16:34 UTC, ashleygmulligan2 approved these changes

2023-07-25 16:35 UTC, merged