fix: recordHook asyncing/awaiting
FlatFilers/flatfile-plugins pull request #207
Opened 2023-08-25 18:22 UTC by carlbrugger

2023-08-25 19:34 UTC, dboskovic commented on plugins/record-hook/src/RecordHook.ts
> +      () => recordsData.records
I think this is actually a problem. If too hooks initiate at the same time they'll race unless the promise for the records data isn't added to the cache.

2023-08-25 19:35 UTC, dboskovic commented on plugins/record-hook/src/RecordHook.ts
> +    Promise.all(records.map((record) => handler(record, event)))
Should we consider not running all at once?

2023-08-28 16:08 UTC, ashleygmulligan2 requested changes

2023-08-28 16:08 UTC, carlbrugger commented on plugins/record-hook/src/RecordHook.ts
> +    console.error(`Error getting records: ${e}`)
Good to know. I'll switch it back.

2023-08-28 16:11 UTC, ashleygmulligan2 submitted a review, later dismissed

2023-09-12 19:02 UTC, bangarang approved these changes

2023-09-12 19:02 UTC, merged