296 test coverage on all things record hooks
FlatFilers/flatfile-plugins pull request #301
Opened 2023-11-03 03:46 UTC by madaley1

Added some extrapolated tests, but to be honest I'm a bit at a loss on how else to test it. I'll pick it up in the morning and see if I can figure out some other tests to write other than testing valid and invalid values as those are testing the record methods more than they are the record hook.

2023-11-08 15:07 UTC, carlbrugger requested changes

2023-11-08 15:07 UTC, carlbrugger commented on plugins/record-hook/src/tests/bulkRecordHook.messages.e2e.spec.ts
> +    it('correctly assigns metadata', async () => {
```suggestion
  describe('Assigns messages without assigning a new value', () => {
    it('correctly assigns messages', async () => {
```

2023-11-08 15:07 UTC, carlbrugger commented on plugins/record-hook/src/tests/recordHook.messages.e2e.spec.ts
> +    it('correctly assigns metadata', async () => {
```suggestion
  describe('Assigns messages without assigning a new value', () => {
    it('correctly assigns messages', async () => {
```

2023-11-08 15:07 UTC, carlbrugger commented on plugins/record-hook/src/tests/recordHook.messages.e2e.spec.ts
> +      console.dir(records[records.length - 2].values['name'].messages)
debug code

2023-11-08 15:07 UTC, carlbrugger commented on plugins/record-hook/src/tests/bulkRecordHook.messages.e2e.spec.ts
> +      console.dir(records[records.length - 2].values['name'].messages)
debug code

2023-11-27 15:39 UTC, ashleygmulligan2 commented
@madaley1 - can you keep chugging along on this over the week? Not urgent necessarily, but don't want the work to get lost.

2023-11-27 16:07 UTC, carlbrugger commented
@madaley1 I think this is ready to go once the conflict is resolved

2023-11-27 19:10 UTC, madaley1 commented
Hey @carlbrugger @ashleygmulligan2, this should be ready to ship whenever you get a moment to review!

2023-11-27 19:13 UTC, merged